[versions]
accompanist = "0.29.2-rc"
androidxActivity = "1.7.0"
androidxAppCompat = "1.6.1"
apollo = "3.7.5"
compose = "1.4.0"
compose-compiler = "1.4.4-dev-k1.8.20-RC-88d9f3a8232"
kotlin = "1.8.20-RC"
glide = "4.12.0"
material3 = "1.1.0-beta01"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompanist" }
accompanist-pager = { module = "com.google.accompanist:accompanist-pager", version.ref = "accompanist" }
accompanist-pager-indicators = { module = "com.google.accompanist:accompanist-pager-indicators", version.ref = "accompanist" }
accompanist-systemuicontroller = { module = "com.google.accompanist:accompanist-systemuicontroller", version.ref = "accompanist" }
android-gradle-plugin = "com.android.tools.build:gradle:7.4.2"
apollo-adapters = { module = "com.apollographql.apollo3:apollo-adapters" }
apollo-normalized-cache = { module = "com.apollographql.apollo3:apollo-normalized-cache" }
apollo-normalized-cache-sqlite = { module = "com.apollographql.apollo3:apollo-normalized-cache-sqlite" }
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime" }
browser = "androidx.browser:browser:1.5.0"
cardview = "androidx.cardview:cardview:1.0.0"
shared-preferences = "androidx.preference:preference:1.2.0"
coil-compose = "io.coil-kt:coil-compose:2.2.2"
compose-foundation-layout = { module = "androidx.compose.foundation:foundation-layout", version.ref = "compose" }
compose-material = { module = "androidx.compose.material:material", version.ref = "compose" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-runtime = { module = "androidx.compose.runtime:runtime", version.ref = "compose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-graphics = { module = "androidx.compose.ui:ui-graphics", version.ref = "compose" }
compose-ui-manifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "compose" }
compose-ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
constraintlayout = "androidx.constraintlayout:constraintlayout:2.1.4"
desugar-jdk-libs = "com.android.tools:desugar_jdk_libs:2.0.2"
espresso-core = "androidx.test.espresso:espresso-core:3.5.1"
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-bom = "com.google.firebase:firebase-bom:31.2.3"
firebase-config = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics-gradle = "com.google.firebase:firebase-crashlytics-gradle:2.9.4"
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide-runtime = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
google-services = "com.google.gms:google-services:4.3.15"
graphql-kotlin-spring-server = "com.expediagroup:graphql-kotlin-spring-server:6.4.0"
junit = "junit:junit:4.13.2"
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.6.4"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4"
kotlinx-coroutines-play-services = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.6.4"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.0"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0"
layouts = "org.apmem.tools:layouts:1.10"
lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.6.1"
lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.6.0"
material = "com.google.android.material:material:1.8.0"
multidex = "com.android.support:multidex:1.0.3"
navigation-compose = "androidx.navigation:navigation-compose:2.5.3"
okhttp = "com.squareup.okhttp3:okhttp:4.10.0"
openfeedback = "io.openfeedback:feedback-android-sdk-ui:0.0.7"
percentlayout = "androidx.percentlayout:percentlayout:1.0.0"
play-services-auth = "com.google.android.gms:play-services-auth:20.4.1"
vectordrawable = "androidx.vectordrawable:vectordrawable:1.1.0"


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version = "2.5.6" }
appengine = { id = "com.google.cloud.tools.appengine", version = "2.4.2" }
