[versions]
version-code = "1456"
sdk-compile = "34"
sdk-min = "24"
androidxActivity = "1.8.2"
androidxAppCompat = "1.6.1"
androidxLifecycle = "2.7.0"
apollo = "4.0.0-beta.5"
compose = "1.6.3"
android-gradle-plugin = "8.2.2"
compose-compiler = "1.5.11"
kotlin = "1.9.23"
material3 = "1.2.0"
google-services-plugin = "4.4.1"
crashlytics-plugin = "2.9.9"
moko = "0.24.0-alpha-5"
moko-graphics = "0.9.0"
compose-mp = "1.6.1"
datastore = "1.1.0-beta02"
skie = "0.6.2"
firebase = "1.11.1"
koin = "3.5.3"
precompose = "1.6.0-rc02"
compose-plugin = "1.6.1"
image-loader = "1.7.8"
pullrefresh = "1.3.0"
androidx-wear-compose = "1.3.0"
playServicesWearable = "18.1.0"
compose-ui-tooling = "1.3.0"
horologist = "0.6.5"
kprefs = "1.7.2"

[libraries]
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-activity = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivity" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppCompat" }
androidx-lifecycle-runtimeCompose = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidxLifecycle" }
apollo-adapters = { module = "com.apollographql.apollo3:apollo-adapters" }
apollo-normalized-cache = { module = "com.apollographql.apollo3:apollo-normalized-cache" }
apollo-normalized-cache-sqlite = { module = "com.apollographql.apollo3:apollo-normalized-cache-sqlite" }
apollo-runtime = { module = "com.apollographql.apollo3:apollo-runtime" }
shared-preferences = "androidx.preference:preference:1.2.1"
coil-compose = "io.coil-kt:coil-compose:2.5.0"
qdsfdhvh-imageloader = { module = "io.github.qdsfdhvh:image-loader", version.ref = "image-loader" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
compose-material = { group = "androidx.compose.material", name = "material", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
espresso-core = "androidx.test.espresso:espresso-core:3.5.0"
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics-ktx" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx" }
firebase-bom = "com.google.firebase:firebase-bom:32.7.2"
firebase-crashlytics-ktx = { module = "com.google.firebase:firebase-crashlytics-ktx" }
firebase-inappmessaging = { module = "com.google.firebase:firebase-inappmessaging-display-ktx" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging" }
google-services = "com.google.gms:google-services:4.4.1"
graphql-kotlin-spring-server = "com.expediagroup:graphql-kotlin-spring-server:6.4.0"
junit = "junit:junit:4.13.2"
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }
kotlinx-coroutines-android = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
kotlinx-coroutines-core = "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.7.3"
kotlinx-coroutines-play-services = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services:1.7.3"
kotlinx-datetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.5.0"
kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"
lifecycle-runtime-ktx = "androidx.lifecycle:lifecycle-runtime-ktx:2.7.0"
lifecycle-viewmodel-compose = "androidx.lifecycle:lifecycle-viewmodel-compose:2.7.0"
material = "com.google.android.material:material:1.11.0"
navigation-compose = "androidx.navigation:navigation-compose:2.7.7"
openfeedback = "io.openfeedback:openfeedback:0.2.1"
openfeedback-m3 = "io.openfeedback:openfeedback-m3:0.2.1"
play-services-auth = "com.google.android.gms:play-services-auth:20.7.0"
moko-resources = { module = "dev.icerock.moko:resources", version.ref = "moko" }
moko-compose = { module = "dev.icerock.moko:resources-compose", version.ref = "moko" }
moko-graphics = { module = "dev.icerock.moko:graphics", version.ref = "moko-graphics" }
compose-mp-icons = { module = "org.jetbrains.compose.material:material-icons-extended-desktop", version.ref = "compose-mp" }
androidx-datastore-preferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
androidx-datastore-preferences-core = { group = "androidx.datastore", name = "datastore-preferences-core", version.ref = "datastore" }
firebase-installations = { module = "dev.gitlive:firebase-installations", version.ref = "firebase" }
firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "firebase" }
precompose = { module = "moe.tlaster:precompose", version.ref = "precompose" }
precompose-viewmodel = { module = "moe.tlaster:precompose-viewmodel", version.ref = "precompose" }
precompose-koin = { module = "moe.tlaster:precompose-koin", version.ref = "precompose" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "android-gradle-plugin" }
firebase-crashlytics-gradlePlugin = { group = "com.google.firebase", name = "firebase-crashlytics-gradle", version.ref = "crashlytics-plugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
materii-pullrefresh = { group = "dev.materii.pullrefresh", name = "pullrefresh", version.ref = "pullrefresh" }

# Wear dependencies
play-services-wearable = { group = "com.google.android.gms", name = "play-services-wearable", version.ref = "playServicesWearable" }
androidx-splashscreen = "androidx.core:core-splashscreen:1.0.1"
wear-compose-material = { module = "androidx.wear.compose:compose-material", version.ref = "androidx-wear-compose" }
wear-compose-foundation = { module = "androidx.wear.compose:compose-foundation", version.ref = "androidx-wear-compose" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
horologist-composables = { module = "com.google.android.horologist:horologist-composables", version.ref = "horologist" }
horologist-compose-layout = { module = "com.google.android.horologist:horologist-compose-layout", version.ref = "horologist" }
horologist-compose-material = { module = "com.google.android.horologist:horologist-compose-material", version.ref = "horologist" }
horologist-auth-ui = { module = "com.google.android.horologist:horologist-auth-ui", version.ref = "horologist" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidx-compose-ui-tooling = { module = "androidx.wear.compose:compose-ui-tooling", version.ref = "compose-ui-tooling" }
wear-compose-navigation = { module = "androidx.wear.compose:compose-navigation", version.ref = "androidx-wear-compose" }
desugar-jdk-libs = "com.android.tools:desugar_jdk_libs:2.0.4"
kprefs = { module = "org.jraf:kprefs", version.ref = "kprefs" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle-plugin" }
android-library = { id = "com.android.library", version.ref = "android-gradle-plugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
apollo = { id = "com.apollographql.apollo3", version.ref = "apollo" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kmp = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services-plugin" }
crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytics-plugin" }
moko = { id = "dev.icerock.mobile.multiplatform-resources", version.ref = "moko" }
skie = { id = "co.touchlab.skie", version.ref = "skie" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }

## Custom plugins
androidmakers-android-application = { id = "fr.androidmakers.android.application", version = "unspecified" }
androidmakers-kmp-library = { id = "fr.androidmakers.kmp.library", version = "unspecified" }
androidmakers-android-compose = { id = "fr.androidmakers.android.compose", version = "unspecified" }
androidmakers-android-signing = { id = "fr.androidmakers.android.signing", version = "unspecified" }
